import { Familjen_Grotesk } from 'next/font/google';
import './globals.css';

const familjen_Grotesk = Familjen_Grotesk({
  subsets: ['latin'],
  weight: '700',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={familjen_Grotesk.className}>{children}</body>
    </html>
  );
}
